services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  server:
    container_name: server
    env_file: .env
    build:
      context: .
      dockerfile: .docker/Dockerfile
