/**
 * @file Automatically generated by barrelsby.
 */

export * from './method-delete'
export * from './method-get'
export * from './method-patch'
export * from './method-post'
export * from './method-put'
export * from './method'
